In [39]:
import numpy as np
arr = np.array((10,20,30,40,50))
print(arr)

[10 20 30 40 50]


In [41]:
import numpy as np
arr_2D = np.array([[1,2,3],[4,5,6]])
print(arr_2D)

[[1 2 3]
 [4 5 6]]


In [43]:
import numpy as np
lst = [10, 20, 30, 40, 50]
arr = np.array(lst, dtype = float)
print(arr)

[10. 20. 30. 40. 50.]


In [45]:
import numpy as np
names = np.array(['Tom', 'Anna', 'Lily'])
joining_dates = np.array(['2007-06-01','2012-10-15','2012-12-01'], dtype='M')
age = np.array([45,35,40])
print('Data type of names is: ',names.dtype)
print('Data type of names is: ',joining_dates.dtype)
print('Data type of names is: ',age.dtype)

Data type of names is:  <U4
Data type of names is:  datetime64[D]
Data type of names is:  int32


In [47]:
import numpy as np
int_arr = np.array([1,2,3,4,5])

# Method 1 - create a new array
str_arr = np.array(int_arr, dtype='U')
print(str_arr)

#Method 2 - use data type as function
float_arr = np.float32(int_arr)
print(float_arr)

#Method 3 - Use astype() function
cmplx_arr = int_arr.astype(complex)
print(cmplx_arr)

['1' '2' '3' '4' '5']
[1. 2. 3. 4. 5.]
[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]


In [49]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype = float)

#Shape 
print('Shape is:',arr.shape)

#Ndim
print('Ndim is:',arr.ndim)

#Size
print('Size is:',arr.size)

#ItemSize
print('ItemSize is:',arr.itemsize)

#Transpose
print(arr.T)

Shape is: (3, 3)
Ndim is: 2
Size is: 9
ItemSize is: 8
[[1. 4. 7.]
 [2. 5. 8.]
 [3. 6. 9.]]


Numpy - In-built Functions

In [53]:
import numpy as np

#Create an empty 3 by 2 array
empty_arr = np.empty([3,2], dtype = int)
print(empty_arr)

[[-1785349776         384]
 [          0           0]
 [          1           0]]


In [55]:
import numpy as np

#Create a 2 by 2 array initialized by 0
zeros_arr = np.zeros([2,2])
print(zeros_arr)

#Create a one dimensional array initialized by 1
ones_arr = np.ones(5, dtype = int)
print(ones_arr)

[[0. 0.]
 [0. 0.]]
[1 1 1 1 1]


In [57]:
import numpy as np

#Create a 3 by 3 array initialized by 10

full_arr = np.full([3,3], 10, dtype = int)
print(full_arr)

[[10 10 10]
 [10 10 10]
 [10 10 10]]
